{% set name = "blend_modes" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54e0703be83097a94af792e52a21fbbd3af20a690b21c9175283e216762c123a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python >=3.5
    - pip
  run:
    - numpy
    - python >=3.5

test:
  imports:
    - blend_modes

about:
  home: http://github.com/flrs/blend_modes
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Image processing blend modes in Python'

  description: |
    The Blend Modes package enables blending different images,
    or image layers, by means of blend modes. These modes are commonly found
    in graphics programs like Adobe Photoshop or GIMP.
  doc_url: http://blend_modes.readthedocs.io/
  dev_url: https://github.com/flrs/blend_modes

extra:
  recipe-maintainers:
    - flrs
