travis:
  secure:
    BINSTAR_TOKEN: CAJyaim73RPP2zKjQkGQuju7ALbh7wHAuxhoL0DBJDPO6mr3m5fBRw7yDYYODdJNaM66QIA3IvaM7cAxrzHAfTzNbzeauKwEplqn+lxgGlPuugwxnQyMshJPykmHLXwhnyIqpQmskJHIL8+xTHNyAGfC/npi6AYkUJuX3rS8uesBOUa0ToVLPyF0V5rkoZjeQYn7AJXdAkpTAjPwqsSUlV25CZ7c1WEcM7iqD0veY8gX8uBpDEM/8pOeW24KbZNpW2pMojG2pUHiIMlbpGuEY5Hg2mg1DwoAIxtrRebSPQ2KufRg0p4B+7ZGtDlbjlz/GNoYlvqhMVzUCCLfDasdPo/LTnqcZ+LJwaj4v9l9rvzEE/c4kORPkdAsIXZZmuI69FQ4VqHVAnx5dbbcuyKgy7kCcF9GKmC+1Shb6Qg+vJ07e6dwVBxJkeuL/WVGpZ6n7Mlrsi8Qfu+H7yRlOwzhKnBbOmq4eiPUTemw3fv7jcjruCeHnj1E5pAAp8KKOusl35Nm0yg8RnBScx8lMF6cezVRC0TYUwAHcQnAP88p0GB34sWJ8SBa/cQum4BSEheM1d6puIMUJOpk3CA5qHgEPW+bRlZKSttQbBRiu7jSRUo712VCQmWiCC3a/geAOwqKCjY2izXJ9h9X1KyLctexqlZv2qobVUgOcilZvCHG4vs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
